# 应用服务 WEB 访问端口
server:
  port: 8081
# 应用名称
spring:
  application:
    name: spring_ioc_test01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/reggie_22_11_18?serverTimezone=UTC
    # 数据库用户名&密码：
    username: root
    password: 123456
#mybatis plus 设置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
      # 关闭MP3.0自带的banner
      banner: false
  db-config:
    #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
    id-type: ASSIGN_ID
  # 默认数据库表下划线命名
  #table-underline: true

reggie:
  path: D:\tsetimg\


